export const profile = {
  name: "Bhumit Singh",
  initials: "BS",
  location: "Indore, India",
  email: "bhumits893@gmail.com",
  phone: "+91 9752886328",
  github: "https://github.com/bhumitsingh856-cyber",
  linkedin: "https://linkedin.com/in/bhumit-singh-220015327",
  instagram: "https://www.instagram.com/crazyx148",
  dob: "March 18, 2007",
  roles: [
    "Full-stack Engineer",
    "Generative AI",
    "Agentic AI",
    "AI & ML",
    "Learning",
    "Building",
    "Improving",
    "Process",
    "Curious",
  ],
  about:
    "Full-Stack AI Engineer specializing in building LLM applications and Agentic Systems , I design and develop end-to-end AI products accress the full stack - AI Orchestration , frontend and backend",
  bio: [
    "I build software at the intersection of full-stack engineering and applied AI — multi-agent systems, retrieval pipelines, and the interfaces that make them feel inevitable.",
    "Currently a B.Tech CSE (AI & ML) undergrad at IPS Academy, Indore. I ship projects end-to-end, from data layer to interaction design.",
  ],
  education: [
    {
      title: "B.Tech, Computer Science (AI & ML)",
      org: "IPS Academy, Indore",
      period: "2024 — 2028",
      meta: "CGPA 8.8",
    },
    {
      title: "12th Grade — CBSE",
      org: "Kendriya Vidyalaya AFS Amla",
      period: "2023 — 2024",
      meta: "82.5%",
    },
    {
      title: "10th Grade — CBSE",
      org: "Kendriya Vidyalaya AFS Amla",
      period: "2021 — 2022",
      meta: "75%",
    },
  ],
  skills: {
    Languages: ["Python", "TypeScript", "Java"],
    Frontend: ["React", "Next.js", "Tailwind CSS"],
    Backend: ["Express", "FastAPI", "MongoDB", "PostgreSQL", "SQL"],
    "AI / ML": ["LangChain", "LangGraph", "RAG", "LLMs"],
    Tools: ["Clerk", "Cloudinary", "LangSmith"],
  },

  certificates: [
    {
      name: "React(Basic)",
      issuer: "HackerRank",
      year: "2026",
      credentialId: "ccc1bc8c33d4",
      url: "https://www.hackerrank.com/certificates/ccc1bc8c33d4",
      image: "/certificates/hr-react.png",
    },
    {
      name: "AI Foundations",
      issuer: "OpenAI",
      year: "2026",
      credentialId: "rwdrja6vb6",
      url: "https://academy.openai.com/home/certificate/rwdrja6vb6",
      image: "/certificates/oai-ai.png",
    },
    {
      name: "Introduction to Generative AI",
      issuer: "Simplilearn",
      year: "2026",
      credentialId: "10381036",
      url: "https://simpli-web.app.link/e/yGwuCLhAb4b",
      image: "/certificates/sl-genai.png",
    },
    {
      name: "Google skills Badges",
      issuer: "Google Cloud",
      year: "2026",
      credentialId: "null",
      url: "https://www.skills.google/public_profiles/0285c729-e995-4470-b498-294ab8f238b0",
      image: "/certificates/gc-badges.png",
    }, 
  ],
};
